"""Add ScheduledCallbackModel

Revision ID: 1f9a6f2301a5
Revises: ceeaf3c37b2f
Create Date: 2026-07-23 23:22:32.870875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f9a6f2301a5'
down_revision: Union[str, None] = 'ceeaf3c37b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'completed', 'failed', 'cancelled', name='scheduled_callback_status').create(op.get_bind())
    op.create_table('scheduled_callbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('original_run_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'failed', 'cancelled', name='scheduled_callback_status', create_type=False), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('to_number', sa.String(length=32), nullable=False),
    sa.Column('from_number', sa.String(length=32), nullable=False),
    sa.Column('conversation_summary', sa.Text(), nullable=False),
    sa.Column('gathered_context', sa.JSON(), nullable=False),
    sa.Column('callback_chain_depth', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_callbacks_org_id', 'scheduled_callbacks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scheduled_callbacks_original_run_id'), 'scheduled_callbacks', ['original_run_id'], unique=False)
    op.create_index(op.f('ix_scheduled_callbacks_scheduled_for'), 'scheduled_callbacks', ['scheduled_for'], unique=False)
    op.create_index('ix_scheduled_callbacks_status', 'scheduled_callbacks', ['status'], unique=False)
    op.create_index('ix_scheduled_callbacks_workflow_id', 'scheduled_callbacks', ['workflow_id'], unique=False)
    op.create_index('idx_queued_runs_campaign_state_optimized', 'queued_runs', ['campaign_id', 'state'], unique=False, postgresql_where=sa.text("state = 'queued'"))
    op.drop_column('workflow_definitions', 'call_disposition_codes')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='tool_category',
        new_values=['http_api', 'end_call', 'transfer_call', 'calculator', 'native', 'integration', 'mcp', 'wait', 'schedule_callback'],
        affected_columns=[TableReference(table_schema='public', table_name='tools', column_name='category')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='tool_category',
        new_values=['http_api', 'end_call', 'transfer_call', 'calculator', 'native', 'integration', 'mcp', 'wait'],
        affected_columns=[TableReference(table_schema='public', table_name='tools', column_name='category')],
        enum_values_to_rename=[],
    )
    op.add_column('workflow_definitions', sa.Column('call_disposition_codes', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.drop_index('idx_queued_runs_campaign_state_optimized', table_name='queued_runs', postgresql_where=sa.text("state = 'queued'"))
    op.drop_index('ix_scheduled_callbacks_workflow_id', table_name='scheduled_callbacks')
    op.drop_index('ix_scheduled_callbacks_status', table_name='scheduled_callbacks')
    op.drop_index(op.f('ix_scheduled_callbacks_scheduled_for'), table_name='scheduled_callbacks')
    op.drop_index(op.f('ix_scheduled_callbacks_original_run_id'), table_name='scheduled_callbacks')
    op.drop_index('ix_scheduled_callbacks_org_id', table_name='scheduled_callbacks')
    op.drop_table('scheduled_callbacks')
    sa.Enum('pending', 'completed', 'failed', 'cancelled', name='scheduled_callback_status').drop(op.get_bind())
    # ### end Alembic commands ###
