"""fix defaults

Revision ID: 2dfee251117b
Revises: 2159d4ac431a
Create Date: 2025-07-08 14:47:40.747689

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2dfee251117b"
down_revision: str | None = "2159d4ac431a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
