"""Add callback_resume_mode to workflow

Revision ID: 4b6743b8b2a1
Revises: 16fb762c463d
Create Date: 2026-07-24 01:11:03.855952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '4b6743b8b2a1'
down_revision: Union[str, None] = '16fb762c463d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('callback_resume_mode', sa.String(), server_default=sa.text("'fresh'"), nullable=False))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='tool_category',
        new_values=['http_api', 'end_call', 'transfer_call', 'calculator', 'native', 'integration', 'mcp', 'wait'],
        affected_columns=[TableReference(table_schema='public', table_name='tools', column_name='category')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='tool_category',
        new_values=['http_api', 'end_call', 'transfer_call', 'calculator', 'native', 'integration', 'mcp', 'wait', 'schedule_callback'],
        affected_columns=[TableReference(table_schema='public', table_name='tools', column_name='category')],
        enum_values_to_rename=[],
    )
    op.drop_column('workflows', 'callback_resume_mode')
    # ### end Alembic commands ###
