"""add actions

Revision ID: 9f25ff8f3cbd
Revises: d11fbd083a55
Create Date: 2025-06-09 20:16:19.418495

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f25ff8f3cbd"
down_revision: str | None = "d11fbd083a55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("integrations", sa.Column("action", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("integrations", "action")
    # ### end Alembic commands ###
